import { Inter } from "next/font/google";
import 'react-toastify/dist/ReactToastify.css';

import { ToastContainer } from 'react-toastify'; // Import ToastContainer
import NavbarUser from "@/components/users/shared/NavbarUsers";
import FooterUser from "@/components/users/shared/FooterUsers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BlushBelle",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <NavbarUser />
      <div className={inter.className}>
        {children}
      </div>
      <FooterUser />
      <ToastContainer /> {/* Toast container for notifications */}
    </>
  );
}
